station:
  name: WRPI
logger:
  log_format: "%(asctime)s - %(threadName)-10s [%(levelname)s] %(message)s"
  alert_format: "Message type:\t[%(levelname)s]\nTime:\t%(asctime)s\nLocation:\t%(pathname)s: %(lineno)d\nModule:\t%(module)s\nThread:\t%(threadName)s\nFunction:\t%(funcName)s\nMessage:\t%(message)s"
alert:
  threshold:
    cpu: 95
    ram: 95
    power: 50
    storage: 95
  smtp:
    enable: no
    host: "mailserver"
    port: 587
    sender: noreply@example.com
    recipients:
      - me@example.com
    subject: "[WRPI-Alert] WRPI Automation Broadcast System Alert"
    username: "user"
    password: "pwd"
  discord:
    enable: no
    webhook: "YOUR WEB HOOK HERE"
    agent: "AGENT NAME"
    mentions:
      - everyone
path:
  bin: bin
  lib: lib
  log: log
  db: db.json
audio:
  transition_length: 1000
  surpression_factor: 0.3
  formats:
    - .mp3
    - .wav
    - .ogg
    - .m4a
  bitrate: 192k
  loudness: -23
  loudness_tolerant: 1.7
  user_channels:
    -
schedule:
  stationID:
    interval: 1 # hour
    time: "00:00"
  systemMonitor: 
    interval: 3 # minute
    time: ":15"
  mixerDigest:
    interval: 5 # minute
    time: ":30"
  volumeGuard:
    interval: 1 # minute
    time: ":45"
